name: Yarn Validate
on:
  pull_request:
  push:
    branches: [master]

jobs:
  yarn-validate:
    strategy:
      matrix:
        step: ['validate']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
        submodules: 'recursive'

    - uses: actions/setup-node@v3
      with:
        node-version: lts/hydrogen

    - name: ${{ matrix.step }}
      run: |
        yarn install --immutable | grep -v 'YN0013'
        yarn ${{ matrix.step }}
